apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-abvr
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0002-tenant/tkrw-pr712-0075-0002-app/devfile-sample-abvr@sha256:836f647de45afdec8f3d413a1475948a9618a3ce16df2d08c2b1dd595e8c263f
        name: my-nodejs
        resources: {}
status: {}
